"""Dataset generation utilities for the Wu 2003 recycle plant.

Each observation window is generated by:
1. Integrating the 8-state explicit-loop model to a scenario-specific steady
   state (warm start), then collecting 120 time steps over a 2-hour window.
2. Adding Gaussian sensor noise (0.3% of each channel's range).
3. Computing the 66-D (S-B) or 72-D (S-A) summary statistics.

The nominal warm start is computed once per control structure and reused
across all scenarios.  Scenario-specific warm starts are computed on demand.
"""

from __future__ import annotations

from dataclasses import asdict
from pathlib import Path
from typing import Iterable

import jax.numpy as jnp
import numpy as np
import pandas as pd

from cstr_sbi.recycle.physics import (
    NOMINAL_CTRL_SA,
    NOMINAL_CTRL_SB,
    NOMINAL_INLET,
    NOMINAL_THETA,
    NOMINAL_Y0_EXPLICIT,
    QJ_NOM,
    T_SP,
    extract_observations_explicit,
    simulate_to_steady_state_explicit,
    simulate_trajectory_explicit,
)
from cstr_sbi.recycle.scenarios import RecycleScenarioConfig, list_configs
from cstr_sbi.recycle.summaries import (
    RAW_CHANNELS,
    SA_CHANNELS, SA_INDICES,
    SB_CHANNELS, SB_INDICES,
    compute_summaries,
)


# ---------------------------------------------------------------------------
# Default simulation settings
# ---------------------------------------------------------------------------

DEFAULT_N_REPLICATES   = 30
DEFAULT_T_FINAL_H      = 2.0     # h  (2-hour observation window)
DEFAULT_N_SAVE         = 120     # timesteps (1-min resolution)
DEFAULT_SENSOR_NOISE   = 0.003   # 0.3% of channel range


# ---------------------------------------------------------------------------
# Controller vector selection
# ---------------------------------------------------------------------------

def ctrl_for(structure: str, open_loop: bool = False) -> jnp.ndarray:
    """Return the controller vector for a given structure and mode."""
    ctrl = NOMINAL_CTRL_SA if structure == "S-A" else NOMINAL_CTRL_SB
    if not open_loop:
        return ctrl
    # Disable all controllers: zero gains, fix actuators at nominal
    ctrl = ctrl.at[0].set(0.0)               # Kp1 = 0 (Loop 1 inactive)
    ctrl = ctrl.at[3].set(QJ_NOM)            # Qj bias stays at nominal
    ctrl = ctrl.at[4].set(QJ_NOM)            # Qj_min = QJ_NOM (clamps cooling)
    ctrl = ctrl.at[5].set(QJ_NOM)            # Qj_max = QJ_NOM
    ctrl = ctrl.at[7].set(0.0)               # KpR_SA = 0 (Loop 2 S-A inactive)
    ctrl = ctrl.at[10].set(0.0)              # KpR_SB = 0 (Loop 2 S-B inactive)
    ctrl = ctrl.at[17].set(0.0)              # KpV_SA = 0 (Loop 3 S-A inactive)
    ctrl = ctrl.at[20].set(0.0)              # KpV_SB = 0 (Loop 3 S-B inactive)
    return ctrl


def scenario_ctrl(scenario: RecycleScenarioConfig, structure: str) -> jnp.ndarray:
    return ctrl_for(structure, open_loop=(scenario.mode == "open_loop"))


# ---------------------------------------------------------------------------
# Warm-start helpers
# ---------------------------------------------------------------------------

def nominal_warm_start(structure: str = "S-B") -> jnp.ndarray:
    """Nominal closed-loop steady state — computed once, reused across scenarios."""
    return simulate_to_steady_state_explicit(
        NOMINAL_THETA, NOMINAL_INLET,
        ctrl_for(structure),
        NOMINAL_Y0_EXPLICIT,
        t_final=200.0,
    )


def scenario_warm_start(
    scenario: RecycleScenarioConfig,
    structure: str = "S-B",
    t_final: float = 200.0,
) -> jnp.ndarray:
    """Steady state for a specific scenario / control structure."""
    return simulate_to_steady_state_explicit(
        scenario.theta(), NOMINAL_INLET,
        scenario_ctrl(scenario, structure),
        NOMINAL_Y0_EXPLICIT,
        t_final=t_final,
    )


# ---------------------------------------------------------------------------
# Single window
# ---------------------------------------------------------------------------

def deterministic_window(
    scenario: RecycleScenarioConfig,
    *,
    structure: str = "S-B",
    y0: jnp.ndarray | None = None,
    t_final_h: float = DEFAULT_T_FINAL_H,
    n_save: int = DEFAULT_N_SAVE,
) -> tuple[np.ndarray, np.ndarray]:
    """Deterministic raw observations for one scenario.

    Returns ``(t_h, raw_obs)`` where:
    - ``t_h`` shape (n_save,) in hours
    - ``raw_obs`` shape (n_save, 12) with columns RAW_CHANNELS
    """
    if y0 is None:
        y0 = nominal_warm_start(structure)
    ctrl = scenario_ctrl(scenario, structure)
    ts, ys = simulate_trajectory_explicit(
        scenario.theta(), NOMINAL_INLET, ctrl, y0,
        t_final=t_final_h, n_save=n_save,
    )
    raw_obs = extract_observations_explicit(ys, scenario.theta(), ctrl)
    return np.asarray(ts), np.asarray(raw_obs)


# ---------------------------------------------------------------------------
# Noise and replicates
# ---------------------------------------------------------------------------

def _sensor_sigma(obs: np.ndarray, noise_pct: float) -> np.ndarray:
    """Per-channel noise sigma = noise_pct × max(|obs|)."""
    scale = np.maximum(np.max(np.abs(obs), axis=0, keepdims=True), 1e-12)
    return noise_pct * scale


def noisy_replicates(
    base_obs: np.ndarray,
    *,
    n_replicates: int,
    rng: np.random.Generator,
    noise_pct: float = DEFAULT_SENSOR_NOISE,
) -> np.ndarray:
    """Shape (n_replicates, n_t, n_ch) noisy copies of base_obs."""
    sigma = _sensor_sigma(base_obs, noise_pct)
    noise = rng.normal(scale=sigma, size=(n_replicates, *base_obs.shape))
    return base_obs[None] + noise


def structure_view(raw_reps: np.ndarray, structure: str) -> np.ndarray:
    """Project replicates to S-A or S-B channel subset."""
    idx = SA_INDICES if structure == "S-A" else SB_INDICES
    return raw_reps[..., idx]


# ---------------------------------------------------------------------------
# Full dataset generation
# ---------------------------------------------------------------------------

def generate_dataset(
    *,
    n_replicates: int = DEFAULT_N_REPLICATES,
    t_final_h: float = DEFAULT_T_FINAL_H,
    n_save: int = DEFAULT_N_SAVE,
    noise_pct: float = DEFAULT_SENSOR_NOISE,
    seed: int = 20260625,
    configs: list[RecycleScenarioConfig] | None = None,
    scenario_specific_warm_start: bool = False,
) -> dict:
    """Generate the full Wu 2003 observation dataset.

    Parameters
    ----------
    configs : list of scenarios; defaults to all closed-loop + open-loop
    scenario_specific_warm_start : if True, compute a scenario-specific SS
        warm-start for each scenario (slower but more accurate initial state)

    Returns a dict with keys:
        t_h                 : (n_save,) time grid
        observations_sa     : (n_scenarios × n_replicates, n_save, n_sa_ch)
        observations_sb     : (n_scenarios × n_replicates, n_save, n_sb_ch)
        labels              : pd.DataFrame with ground-truth theta
        scenario_table      : pd.DataFrame with scenario descriptions
        deterministic_sa/sb : dict of raw (n_save, 12) arrays per scenario name
        raw_channels, sa_channels, sb_channels : channel name lists
    """
    configs = list_configs() if configs is None else sorted(configs, key=lambda s: s.id)
    rng = np.random.default_rng(seed)

    y0_sa = nominal_warm_start("S-A")
    y0_sb = nominal_warm_start("S-B")

    sa_windows: list[np.ndarray] = []
    sb_windows: list[np.ndarray] = []
    labels: list[dict]           = []
    det_sa: dict[str, np.ndarray] = {}
    det_sb: dict[str, np.ndarray] = {}
    t_grid = None

    for sc in configs:
        ic_sa = (
            scenario_warm_start(sc, "S-A") if scenario_specific_warm_start
            else y0_sa
        )
        ic_sb = (
            scenario_warm_start(sc, "S-B") if scenario_specific_warm_start
            else y0_sb
        )

        t_h, raw_sa = deterministic_window(
            sc, structure="S-A", y0=ic_sa, t_final_h=t_final_h, n_save=n_save,
        )
        _, raw_sb = deterministic_window(
            sc, structure="S-B", y0=ic_sb, t_final_h=t_final_h, n_save=n_save,
        )
        if t_grid is None:
            t_grid = t_h

        det_sa[sc.name] = raw_sa
        det_sb[sc.name] = raw_sb

        sa_reps_raw = noisy_replicates(raw_sa, n_replicates=n_replicates, rng=rng,
                                       noise_pct=noise_pct)
        sb_reps_raw = noisy_replicates(raw_sb, n_replicates=n_replicates, rng=rng,
                                       noise_pct=noise_pct)

        sa_windows.append(structure_view(sa_reps_raw, "S-A"))
        sb_windows.append(structure_view(sb_reps_raw, "S-B"))

        theta = np.asarray(sc.theta(), dtype=float)
        for rep in range(n_replicates):
            labels.append({
                "scenario_id":   sc.id,
                "scenario_name": sc.name,
                "fault_unit":    sc.fault_unit(),
                "mode":          sc.mode,
                "replicate":     rep,
                "alpha":         theta[0],
                "beta_r":        theta[1],
                "eta_col":       theta[2],
                "xi_reb":        theta[3],
                "z_A0_eff":      theta[4],
            })

    # Scenario table
    sc_rows = []
    for sc in configs:
        row = asdict(sc)
        row["theta"] = np.asarray(sc.theta(), dtype=float).tolist()
        sc_rows.append(row)

    return {
        "t_h":              np.asarray(t_grid),
        "observations_sa":  np.concatenate(sa_windows, axis=0),
        "observations_sb":  np.concatenate(sb_windows, axis=0),
        "labels":           pd.DataFrame(labels),
        "scenario_table":   pd.DataFrame(sc_rows).sort_values("id").reset_index(drop=True),
        "deterministic_sa": det_sa,
        "deterministic_sb": det_sb,
        "raw_channels":     RAW_CHANNELS,
        "sa_channels":      SA_CHANNELS,
        "sb_channels":      SB_CHANNELS,
        "n_replicates":     n_replicates,
        "noise_pct":        noise_pct,
        "seed":             seed,
    }


def save_dataset(dataset: dict, path: str | Path) -> Path:
    """Save a generated dataset to ``.npz``."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    labels = dataset["labels"]
    sc_table = dataset["scenario_table"]
    np.savez_compressed(
        path,
        t_h=dataset["t_h"],
        observations_sa=dataset["observations_sa"],
        observations_sb=dataset["observations_sb"],
        labels=labels.to_records(index=False),
        scenario_table=sc_table.to_records(index=False),
        raw_channels=np.asarray(dataset["raw_channels"], dtype=object),
        sa_channels=np.asarray(dataset["sa_channels"],   dtype=object),
        sb_channels=np.asarray(dataset["sb_channels"],   dtype=object),
        n_replicates=np.asarray(dataset["n_replicates"]),
        noise_pct=np.asarray(dataset["noise_pct"]),
        seed=np.asarray(dataset["seed"]),
    )
    return path


def load_dataset(path: str | Path) -> dict:
    """Load a dataset saved by ``save_dataset``."""
    path = Path(path)
    data = np.load(path, allow_pickle=True)
    labels = pd.DataFrame.from_records(data["labels"])
    sc_table = pd.DataFrame.from_records(data["scenario_table"])
    return {
        "t_h":              data["t_h"],
        "observations_sa":  data["observations_sa"],
        "observations_sb":  data["observations_sb"],
        "labels":           labels,
        "scenario_table":   sc_table,
        "raw_channels":     list(data["raw_channels"]),
        "sa_channels":      list(data["sa_channels"]),
        "sb_channels":      list(data["sb_channels"]),
        "n_replicates":     int(data["n_replicates"]),
        "noise_pct":        float(data["noise_pct"]),
        "seed":             int(data["seed"]),
    }
